version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duyphatbk
    ports:
      - "5432:5432"
    networks:
      - order-db_backend-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: duyphatbk@gmail.com
      PGADMIN_DEFAULT_PASSWORD: duyphatbk
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - order-db_backend-network
  # rabbitmq:
  #   image: "rabbitmq:management"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  order-db:
    image: order-db:1.0
    ports:
      - "9092:8090"
    depends_on:
      - postgres
      # - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: duyphatbk
  #     SPRING_RABBITMQ_HOST: rabbitmq
  #     SPRING_RABBITMQ_PORT: 5672
  #     SPRING_RABBITMQ_USERNAME: guest
  #     SPRING_RABBITMQ_PASSWORD: guest
  #     EXCHANGE_NAME: exchange-name
  #     QUEUE_NAME: queue-name
  #     ROUTING_KEY: routing-key
  #     ORDER_QUEUE_NAME: order-queue-name
  #     ORDER_ROUTING_KEY: order-routing-key
    networks:
      - order-db_backend-network
networks:
    order-db_backend-network:
      external: true