version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duyphatbk
    ports:
      - "5432:5432"
    # networks:
    #   - order-db_backend-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: duyphatbk@gmail.com
      PGADMIN_DEFAULT_PASSWORD: duyphatbk
    ports:
      - "5050:80"
    depends_on:
      - postgres
    # networks:
    #   - order-db_backend-network
  order-db:
    image: order-db:1.0
    ports:
      - "9092:9092"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: duyphatbk
#     networks:
#       - order-db_backend-network
# networks:
#     order-db_backend-network:
#       external: true