version: "2"

services:
  rabbitmq-node-1:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-1
    hostname: rabbitmq-node-1
    cpus: "1"
    ports:
      - "15672:15672"
    networks:
      - cluster-network
    volumes:
      - $PWD/storage/rabbitmq-node-1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rabbitmq-node-2:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-2
    hostname: rabbitmq-node-2
    cpus: "1"
    ports:
      - "15673:15672"
    networks:
      - cluster-network
    volumes:
      - $PWD/storage/rabbitmq-node-2:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rabbitmq-node-3:
    image: rabbitmq:3-management
    container_name: rabbitmq-node-3
    hostname: rabbitmq-node-3
    cpus: "1"
    ports:
      - "15674:15672"
    networks:
      - cluster-network
    volumes:
      - $PWD/storage/rabbitmq-node-3:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  haproxy:
    image: haproxy-server:latest
    container_name: haproxy
    hostname: haproxy
    cpus: "1"
    ports:
      - "5672:5672"
      - "1936:1936"
    networks:
      - cluster-network

networks:
  cluster-network:
    driver: bridge
