apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-fe-deploy
  labels:
    app: catalog-fe
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-fe-pod
      tier: frontend
  template:
    metadata:
      name: catalog-fe-pod
      labels:
        app: catalog-fe-pod
        tier: frontend
    spec:
      containers:
      - name: catalog-fe
        image: hoanganhleboy/catalog-fe:latest
        ports:
        - containerPort: 80
        env:
        - name: CONTENT
          value: "This is the string from k8s"
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-fe-service
  labels:
    app: catalog-fe-service
    tier: frontend
spec:
  selector:
    app: catalog-fe-pod
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
